---
title: "DO intervals"
author: "Abby Lewis"
date: "8/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(rLakeAnalyzer)

vw2<- read_csv("../../DO_modeling_data/final_modeling_dataset.csv")
```


TO DO 
- fix piecewise intercepts


Weekly (two week intervals)
```{r}
vw2_week <- vw2
#This section sets it up to divide into weeks
vw2_week$WeeksSinceStart <- floor(vw2_week$DaysSinceStart/14)
repStartEnd <- vw2_week %>%
  filter(DaysSinceStart !=0, 
         DaysSinceStart %% 14 == 0)%>%
  mutate(WeeksSinceStart = WeeksSinceStart - 1) #Duplicate endpoints
vw2_week = vw2_week %>%
  full_join(repStartEnd)%>%
  mutate(Date_start = IntervalStart+WeeksSinceStart*14)%>%
  filter(!is.na(IntervalStart))

slope_temp_wk <- vw2_week %>%
  filter(ClosestStart>0)%>%
  group_by(ClosestStart, WeeksSinceStart) %>%
  summarize(
    temp = mean(Temp),
    Date_start = unique(Date_start),
    Date_end = max(Date),
    IntStart = unique(IntervalStart),
    IntEnd = unique(IntervalEnd),
    Observations_co2 = sum(!is.na(co2_vw_umolL)),
    Observations_o2 = sum(!is.na(Conc)),
    mg_L_day_O2 = mean(scfm)*50*1000000/mean(hypoVolume),
    SSS = unique(SSS),
    temp_sed = mean(Temp),
    temp_init = first(Temp),
    temp_final = last(Temp),
    doc_init = first(DOC_mgL),
    doc_mean = mean(DOC_mgL, na.rm = T),
    Fe_init = first(TFe_mgL),
    Fe_mean = mean(TFe_mgL, na.rm = T),
    o2_init = first(Conc),
    o2_mean = mean(Conc),
    schmidt_min = ifelse(min(schmidt_stability, na.rm = T)%in%c(-Inf,Inf),NA,min(schmidt_stability, na.rm = T)),
    schmidt_mean = mean(schmidt_stability, na.rm = T),
    schmidt_max = ifelse(max(schmidt_stability, na.rm = T)%in%c(-Inf,Inf),NA,max(schmidt_stability, na.rm = T)),
    dist_turnover =as.numeric(difftime(unique(Date_turnover),IntStart, units = "days")),
    thermo_start = first(thermo_depth),
    thermo_end = last(thermo_depth),
    thermo_mean = mean(thermo_depth)
    )

slopes_wk_do <- vw2_week%>%
  filter(ClosestStart>0)%>%
  group_by(ClosestStart, WeeksSinceStart) %>%
  do(intercept_do = as.numeric(lm(Conc~ Date, data = .)$coefficients[1]),
     slope_do = as.numeric(lm(Conc~ Date, data = .)$coefficients[2]))

slopes_wk_co2 <- vw2_week%>%
  filter(ClosestStart>0)%>%
  group_by(ClosestStart, WeeksSinceStart) %>%
  filter(sum(!is.na(co2_vw_umolL))>0)%>%
  do(intercept_co2 = as.numeric(lm(co2_vw_umolL~ Date, data = .)$coefficients[1]),
     slope_co2 = as.numeric(lm(co2_vw_umolL~ Date, data = .)$coefficients[2]))

slopes_wk_dic <- vw2_week%>%
  filter(ClosestStart>0)%>%
  group_by(ClosestStart, WeeksSinceStart) %>%
  filter(sum(!is.na(all_c_umolL))>0)%>%
  do(intercept_dic = as.numeric(lm(all_c_umolL~ Date, data = .)$coefficients[1]),
     slope_dic = as.numeric(lm(all_c_umolL~ Date, data = .)$coefficients[2]))

slope_temp_wk = slope_temp_wk %>%
  left_join(slopes_wk_do, by = c("ClosestStart", "WeeksSinceStart")) %>%
  filter(Date_start != IntEnd) %>%
  mutate(slope_do = unlist(slope_do),
         intercept_do = unlist(intercept_do),
         slope_O2 = slope_do - mg_L_day_O2)%>%
  left_join(slopes_wk_co2%>%
              mutate(slope_co2 = unlist(slope_co2),
                     intercept_co2 = unlist(intercept_co2)), by = c("ClosestStart", "WeeksSinceStart") )%>%
  left_join(slopes_wk_dic%>%
              mutate(slope_dic = unlist(slope_dic),
                     intercept_dic = unlist(intercept_dic)), by = c("ClosestStart", "WeeksSinceStart") )

for(year in 2013:2019){
  seg = vw2_week%>%
    filter(year(Date)==year)%>%
    mutate(Date = as.numeric(Date))%>%
    filter(!is.na(Date))

  breaks = unique(seg$Date_start)
  for (i in 1:length(breaks)){
    seg[paste0("Date",i)] <- (seg$Date-as.numeric(breaks[i]))*ifelse(seg$Date>=breaks[i],1,0)
  }
  
  #CO2
  if(year>=2015){
    mod_co2 = lm(seg$co2_vw_umolL~.,seg[,c("Date",paste0("Date",1:length(breaks)))])
    
    coef_index = 1
    coefs= c(mod_co2$coefficients[2:length(mod_co2$coefficients)])
    coefs[is.na(coefs)]<- 0
    slopes_co2 = coefs
    while(coef_index < length(coefs)){
      slopes_co2[(coef_index+1):length(coefs)] <- slopes_co2[(coef_index+1):length(coefs)] + coefs[coef_index]
      coef_index = coef_index+1
    }
  }else{
    slopes_co2 <- NA
  }
  
  #O2
  mod_o2 = lm(seg$Conc~.,seg[,c("Date",paste0("Date",1:length(breaks)))])
  coef_index = 1
  coefs= c(mod_o2$coefficients[2:length(mod_o2$coefficients)])
  coefs[is.na(coefs)]<- 0
  slopes_o2 = coefs
  while(coef_index < length(coefs)){
    slopes_o2[(coef_index+1):length(coefs)] <- slopes_o2[(coef_index+1):length(coefs)] + coefs[coef_index]
    coef_index = coef_index+1
  }
  
  Date_start = as.Date(c(NA,breaks), origin = "1970-01-01")
  new = data.frame(Date_start,pw_slope_co2 = slopes_co2, pw_slope_o2 = slopes_o2, year, pw_intercept_co2 = mod_co2$coefficients[1], pw_intercept_o2 = mod_o2$coefficients[1])
  if(year>2015){
    output = output%>%
      full_join(new)
  }else{
    output = new
  }
}

slope_temp_wk_2obs <- slope_temp_wk %>%
  filter(Observations_co2 >=2,
         Observations_o2 >=2)

slope_temp_wk = slope_temp_wk%>%
  full_join(output%>% filter(!is.na(Date_start)), by = "Date_start")%>%
  mutate(pw_slope_o2_oxygenation = pw_slope_o2 - mg_L_day_O2)

slope_temp_wk%>%
  filter(Observations_co2 >=2,
         Observations_o2 >=2)%>%
  ggplot(aes(x = slope_co2, y = pw_slope_co2))+
  geom_point()

write.csv(slope_temp_wk, "slope_temp_wk.csv", row.names = F)
```

Months
```{r}
vw2_week$WeeksSinceStart <- floor(vw2_week$DaysSinceStart/30)
repStartEnd <- vw2_week %>%
  filter(DaysSinceStart !=0, 
         DaysSinceStart %% 30 == 0)%>%
  mutate(WeeksSinceStart = WeeksSinceStart - 1) #Duplicate endpoints
vw2_week = vw2_week %>%
  full_join(repStartEnd)%>%
  mutate(Date_start = IntervalStart+WeeksSinceStart*30)%>%
  filter(!is.na(IntervalStart))

slope_temp_wk <- vw2_week %>%
  filter(ClosestStart>0)%>%
  group_by(ClosestStart, WeeksSinceStart) %>%
  summarize(
    temp = mean(Temp),
    Date_start = unique(Date_start),
    Date_end = max(Date),
    IntStart = unique(IntervalStart),
    IntEnd = unique(IntervalEnd),
    Observations_co2 = sum(!is.na(co2_vw_umolL)),
    Observations_o2 = sum(!is.na(Conc)),
    mg_L_day_O2 = mean(scfm)*50*1000000/mean(hypoVolume),
    SSS = unique(SSS),
    temp_sed = mean(Temp),
    temp_init = first(Temp),
    temp_final = last(Temp),
    doc_init = first(DOC_mgL),
    doc_mean = mean(DOC_mgL, na.rm = T),
    Fe_init = first(TFe_mgL),
    Fe_mean = mean(TFe_mgL, na.rm = T),
    o2_init = first(Conc),
    o2_mean = mean(Conc),
    schmidt_min = ifelse(min(schmidt_stability, na.rm = T)%in%c(-Inf,Inf),NA,min(schmidt_stability, na.rm = T)),
    schmidt_mean = mean(schmidt_stability, na.rm = T),
    schmidt_max = ifelse(max(schmidt_stability, na.rm = T)%in%c(-Inf,Inf),NA,max(schmidt_stability, na.rm = T)),
    dist_turnover =as.numeric(difftime(unique(Date_turnover),IntStart, units = "days")),
    thermo_start = first(thermo_depth),
    thermo_end = last(thermo_depth),
    thermo_mean = mean(thermo_depth)
    )

slopes_wk_do <- vw2_week%>%
  filter(ClosestStart>0)%>%
  group_by(ClosestStart, WeeksSinceStart) %>%
  do(intercept_do = as.numeric(lm(Conc~ Date, data = .)$coefficients[1]),
     slope_do = as.numeric(lm(Conc~ Date, data = .)$coefficients[2]))

slopes_wk_co2 <- vw2_week%>%
  filter(ClosestStart>0)%>%
  group_by(ClosestStart, WeeksSinceStart) %>%
  filter(sum(!is.na(co2_vw_umolL))>0)%>%
  do(intercept_co2 = as.numeric(lm(co2_vw_umolL~ Date, data = .)$coefficients[1]),
     slope_co2 = as.numeric(lm(co2_vw_umolL~ Date, data = .)$coefficients[2]))

slopes_wk_dic <- vw2_week%>%
  filter(ClosestStart>0)%>%
  group_by(ClosestStart, WeeksSinceStart) %>%
  filter(sum(!is.na(all_c_umolL))>0)%>%
  do(intercept_dic = as.numeric(lm(all_c_umolL~ Date, data = .)$coefficients[1]),
     slope_dic = as.numeric(lm(all_c_umolL~ Date, data = .)$coefficients[2]))

slope_temp_wk = slope_temp_wk %>%
  left_join(slopes_wk_do, by = c("ClosestStart", "WeeksSinceStart")) %>%
  filter(Date_start != IntEnd) %>%
  mutate(slope_do = unlist(slope_do),
         intercept_do = unlist(intercept_do),
         slope_O2 = slope_do - mg_L_day_O2)%>%
  left_join(slopes_wk_co2%>%
              mutate(slope_co2 = unlist(slope_co2),
                     intercept_co2 = unlist(intercept_co2)), by = c("ClosestStart", "WeeksSinceStart") )%>%
  left_join(slopes_wk_dic%>%
              mutate(slope_dic = unlist(slope_dic),
                     intercept_dic = unlist(intercept_dic)), by = c("ClosestStart", "WeeksSinceStart") )

for(year in 2013:2019){
  seg = vw2_week%>%
    filter(year(Date)==year)%>%
    mutate(Date = as.numeric(Date))%>%
    filter(!is.na(Date))

  breaks = unique(seg$Date_start)
  for (i in 1:length(breaks)){
    seg[paste0("Date",i)] <- (seg$Date-as.numeric(breaks[i]))*ifelse(seg$Date>=breaks[i],1,0)
  }
  
  #CO2
  if(year>=2015){
    mod_co2 = lm(seg$co2_vw_umolL~.,seg[,c("Date",paste0("Date",1:length(breaks)))])
    
    coef_index = 1
    coefs= c(mod_co2$coefficients[2:length(mod_co2$coefficients)])
    coefs[is.na(coefs)]<- 0
    slopes_co2 = coefs
    while(coef_index < length(coefs)){
      slopes_co2[(coef_index+1):length(coefs)] <- slopes_co2[(coef_index+1):length(coefs)] + coefs[coef_index]
      coef_index = coef_index+1
    }
  }else{
    slopes_co2 <- NA
  }
  
  #O2
  mod_o2 = lm(seg$Conc~.,seg[,c("Date",paste0("Date",1:length(breaks)))])
  coef_index = 1
  coefs= c(mod_o2$coefficients[2:length(mod_o2$coefficients)])
  coefs[is.na(coefs)]<- 0
  slopes_o2 = coefs
  while(coef_index < length(coefs)){
    slopes_o2[(coef_index+1):length(coefs)] <- slopes_o2[(coef_index+1):length(coefs)] + coefs[coef_index]
    coef_index = coef_index+1
  }
  
  Date_start = as.Date(c(NA,breaks), origin = "1970-01-01")
  new = data.frame(Date_start,pw_slope_co2 = slopes_co2, pw_slope_o2 = slopes_o2, year, pw_intercept_co2 = mod_co2$coefficients[1], pw_intercept_o2 = mod_o2$coefficients[1])
  if(year>2015){
    output = output%>%
      full_join(new)
  }else{
    output = new
  }
  
  Date = min(seg$Date):max(seg$Date)
  pred = data.frame(Date)
  for (i in 1:length(breaks)){
    pred[paste0("Date",i)] <- (pred$Date-as.numeric(breaks[i]))*ifelse(pred$Date>=breaks[i],1,0)
  }
  
  pred$predicted_o2 = predict(mod_o2,pred)
  
  p = pred%>%
    ggplot(aes(x = Date))+
    geom_line(aes(y = predicted_o2), color = "red")+
    geom_point(aes(y = Conc), data = seg)+
    geom_vline(xintercept = breaks)
  print(p)
  
  if (year>=2015){
    pred$predicted_co2 = predict(mod_co2,pred)
    p = pred%>%
      ggplot(aes(x = Date))+
      geom_line(aes(y = predicted_co2), color = "red")+
      geom_point(aes(y = co2_vw_umolL), data = seg)+
      geom_vline(xintercept = breaks)
    print(p)
  }
}

slope_temp_wk_2obs <- slope_temp_wk %>%
  filter(Observations_co2 >=2,
         Observations_o2 >=2)

slope_temp_month = slope_temp_wk%>%
  full_join(output%>% filter(!is.na(Date_start)), by = "Date_start")%>%
  mutate(pw_slope_o2_oxygenation = pw_slope_o2 - mg_L_day_O2)

slope_temp_month%>%
  filter(Observations_co2 >=2,
         Observations_o2 >=2)%>%
  ggplot(aes(x = slope_co2, y = pw_slope_co2))+
  geom_point()

write.csv(slope_temp_month, "slope_temp_month.csv", row.names = F)
```



```{r}
#This does the same thing, but for intervals
vw2_int <- vw2

slope_temp_int <- vw2_int %>%
  filter(ClosestStart>0)%>%
  group_by(ClosestStart) %>%
  summarize(
    temp = mean(Temp),
    Date_start = min(Date),
    Date_end = max(Date),
    IntStart = unique(IntervalStart),
    IntEnd = unique(IntervalEnd),
    Observations_co2 = sum(!is.na(co2_vw_umolL)),
    Observations_o2 = sum(!is.na(Conc)),
    mg_L_day_O2 = mean(scfm)*50*1000000/mean(hypoVolume),
    SSS = unique(SSS),
    temp_sed = mean(Temp),
    temp_init = first(Temp),
    temp_final = last(Temp),
    doc_init = first(DOC_mgL),
    doc_mean = mean(DOC_mgL, na.rm = T),
    Fe_init = first(TFe_mgL),
    Fe_mean = mean(TFe_mgL, na.rm = T),
    o2_init = first(Conc),
    o2_mean = mean(Conc),
    schmidt_min = ifelse(min(schmidt_stability, na.rm = T)%in%c(-Inf,Inf),NA,min(schmidt_stability, na.rm = T)),
    schmidt_mean = mean(schmidt_stability, na.rm = T),
    schmidt_max = ifelse(max(schmidt_stability, na.rm = T)%in%c(-Inf,Inf),NA,max(schmidt_stability, na.rm = T)),
    dist_turnover =as.numeric(difftime(unique(Date_turnover),IntStart, units = "days")),
    thermo_start = first(thermo_depth),
    thermo_end = last(thermo_depth),
    thermo_mean = mean(thermo_depth))

slopes_int_do <- vw2_int%>%
  filter(ClosestStart>0)%>%
  group_by(ClosestStart) %>%
  do(intercept_do = as.numeric(lm(Conc~ Date, data = .)$coefficients[1]),
     slope_do = as.numeric(lm(Conc~ Date, data = .)$coefficients[2]))

slopes_int_co2 <- vw2_int%>%
  filter(ClosestStart>0)%>%
  group_by(ClosestStart) %>%
  filter(sum(!is.na(co2_vw_umolL))>0)%>%
  do(intercept_co2 = as.numeric(lm(co2_vw_umolL~ Date, data = .)$coefficients[1]),
     slope_co2 = as.numeric(lm(co2_vw_umolL~ Date, data = .)$coefficients[2]))

slopes_wk_dic <- vw2_week%>%
  filter(ClosestStart>0)%>%
  group_by(ClosestStart) %>%
  filter(sum(!is.na(all_c_umolL))>0)%>%
  do(intercept_dic = as.numeric(lm(all_c_umolL~ Date, data = .)$coefficients[1]),
     slope_dic = as.numeric(lm(all_c_umolL~ Date, data = .)$coefficients[2]))

slope_temp_int = slope_temp_int %>%
  left_join(slopes_int_do, by = c("ClosestStart")) %>%
  filter(Date_start != IntEnd) %>%
  mutate(slope_do = unlist(slope_do),
         intercept_do = unlist(intercept_do),
         slope_O2 = slope_do - mg_L_day_O2)%>%
  left_join(slopes_int_co2%>%
              mutate(slope_co2 = unlist(slope_co2),
                     intercept_co2 = unlist(intercept_co2)), by = c("ClosestStart") )%>%
  left_join(slopes_wk_dic%>%
              mutate(slope_dic = unlist(slope_dic),
                     intercept_dic = unlist(intercept_dic)), by = c("ClosestStart") )


for(year in 2013:2019){
  seg = vw2_int%>%
    filter(year(Date)==year)%>%
    mutate(Date = as.numeric(Date))%>%
    filter(!is.na(Date), !is.na(IntervalStart))

  breaks = unique(seg$IntervalStart)
  for (i in 1:length(breaks)){
    seg[paste0("Date",i)] <- (seg$Date-as.numeric(breaks[i]))*ifelse(seg$Date>=breaks[i],1,0)
  }
  
  #CO2
  if(year>=2015){
    mod_co2 = lm(seg$co2_vw_umolL~.,seg[,c("Date",paste0("Date",1:length(breaks)))])
    
    coef_index = 1
    coefs= c(mod_co2$coefficients[2:length(mod_co2$coefficients)])
    coefs[is.na(coefs)]<- 0
    slopes_co2 = coefs
    while(coef_index < length(coefs)){
      slopes_co2[(coef_index+1):length(coefs)] <- slopes_co2[(coef_index+1):length(coefs)] + coefs[coef_index]
      coef_index = coef_index+1
    }
  }else{
    slopes_co2 <- NA
  }
  
  #O2
  mod_o2 = lm(seg$Conc~.,seg[,c("Date",paste0("Date",1:length(breaks)))])
  coef_index = 1
  coefs= c(mod_o2$coefficients[2:length(mod_o2$coefficients)])
  coefs[is.na(coefs)]<- 0
  slopes_o2 = coefs
  while(coef_index < length(coefs)){
    slopes_o2[(coef_index+1):length(coefs)] <- slopes_o2[(coef_index+1):length(coefs)] + coefs[coef_index]
    coef_index = coef_index+1
  }
  
  Date_start = as.Date(c(NA,breaks), origin = "1970-01-01")
  new = data.frame(Date_start,pw_slope_co2 = slopes_co2, pw_slope_o2 = slopes_o2, year, pw_intercept_co2 = mod_co2$coefficients[1], pw_intercept_o2 = mod_o2$coefficients[1])
  if(year>2015){
    output = output%>%
      full_join(new)
  }else{
    output = new
  }
}

slope_temp_int = slope_temp_int%>%
  full_join(output%>% filter(!is.na(Date_start)), by = "Date_start")%>%
  mutate(pw_slope_o2_oxygenation = pw_slope_o2 - mg_L_day_O2)

slope_temp_int_3obs <- slope_temp_int %>%
  filter(Observations_co2 >=2,
         Observations_o2 >=2)
write.csv(slope_temp_int, "slope_temp_int.csv", row.names = F)
```


Plots of DO

Week
```{r}
lim_bot <- min(-slope_temp_wk_2obs$slope_O2)
lim_top <- max(-slope_temp_wk_2obs$slope_O2)

jet.colors <- colorRampPalette(c("#00007F", "blue", "#007FFF", "cyan", "#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000"))

g0 <- vw2_week%>%
  filter(ClosestStart>0) 

slopes_for_plot <- slope_temp_wk_2obs %>%
  filter(!is.na(slope_do)) %>%
  mutate(y0 = slope_do*as.numeric(Date_start)+intercept_do,
         y1 = slope_do*as.numeric(Date_end)+intercept_do,
         y1_o2 = y0 + slope_O2*as.numeric(Date_end-Date_start),
         Year = year(Date_start))

g0 %>%
  mutate(Year = year(Date))%>%
  ggplot(aes(x = as_datetime(Date),y = Conc))+
  geom_segment(aes(x = as_datetime(Date_start), 
                 y = y0, 
                 xend = as_datetime(Date_end), 
                 yend = y1, color = -slope_O2), data = slopes_for_plot,
             lwd = 3)+
  scale_color_gradientn(colours=jet.colors(7), limits = c(lim_bot,lim_top),na.value = "white")+
  geom_point(size = 2, alpha = 0.5, aes(shape = Source))+
  #geom_vline(xintercept = on)+
  #geom_vline(xintercept = off,lty=2)+
  facet_grid(cols = vars(Year), scales = "free_x",space = "free_x")+
  ylab("Average hypolimnetic DO (mg/L)")+
  xlab("")+
  theme_bw()+
  theme(axis.text.x=element_blank(),
        axis.ticks = element_blank(),
        text = element_text(size = 13))
```

Month
```{r}
lim_bot <- min(-slope_temp_month_3obs$slope_O2)
lim_top <- max(-slope_temp_month_3obs$slope_O2)

jet.colors <- colorRampPalette(c("#00007F", "blue", "#007FFF", "cyan", "#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000"))

g0 <- vw2_week%>%
  filter(ClosestStart>0) 

slopes_for_plot <- slope_temp_month_3obs %>%
  filter(!is.na(slope_do)) %>%
  mutate(y0 = slope_do*as.numeric(Date_start)+intercept_do,
         y1 = slope_do*as.numeric(Date_end)+intercept_do,
         y1_o2 = y0 + slope_O2*as.numeric(Date_end-Date_start),
         Year = year(Date_start))

p = g0 %>%
  mutate(Year = year(Date))%>%
  ggplot(aes(x = as_datetime(Date),y = Conc))+
  geom_segment(aes(x = as_datetime(Date_start), 
                 y = y0, 
                 xend = as_datetime(Date_end), 
                 yend = y1, color = -slope_O2), data = slopes_for_plot,
             lwd = 3)+
  scale_color_gradientn(colours=jet.colors(7), limits = c(lim_bot,lim_top),na.value = "white")+
  geom_point(size = 2, pch = 1, alpha = 0.5)+
  #geom_vline(xintercept = on)+
  #geom_vline(xintercept = off,lty=2)+
  facet_grid(cols = vars(Year), scales = "free_x",space = "free_x")+
  ylab("Average hypolimnetic DO (mg/L)")+
  xlab("")+
  theme_bw()+
  theme(axis.text.x=element_blank(),
        axis.ticks = element_blank(),
        text = element_text(size = 13))

p

jpeg("o2_month_intervals.jpg",width = 6, height = 4, units = "in", res = 300)
p
dev.off()
```

Interval
```{r}
lim_bot <- min(-slope_temp_int_3obs$slope_O2)
lim_top <- max(-slope_temp_int_3obs$slope_O2)

jet.colors <- colorRampPalette(c("#00007F", "blue", "#007FFF", "cyan", "#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000"))

g0 <- vw2_week%>%
  filter(ClosestStart>0) 

slopes_for_plot <- slope_temp_int_3obs %>%
  filter(!is.na(slope_do)) %>%
  mutate(y0 = slope_do*as.numeric(Date_start)+intercept_do,
         y1 = slope_do*as.numeric(Date_end)+intercept_do,
         y1_o2 = y0 + slope_O2*as.numeric(Date_end-Date_start),
         Year = year(Date_start))

g0 %>%
  mutate(Year = year(Date))%>%
  ggplot(aes(x = as_datetime(Date),y = Conc))+
  geom_segment(aes(x = as_datetime(Date_start), 
                 y = y0, 
                 xend = as_datetime(Date_end), 
                 yend = y1, color = -slope_O2), data = slopes_for_plot,
             lwd = 3)+
  scale_color_gradientn(colours=jet.colors(7), limits = c(lim_bot,lim_top),na.value = "white")+
  geom_point(size = 2, pch = 1, alpha = 0.5)+
  #geom_vline(xintercept = on)+
  #geom_vline(xintercept = off,lty=2)+
  facet_grid(cols = vars(Year), scales = "free_x",space = "free_x")+
  ylab("Average hypolimnetic DO (mg/L)")+
  xlab("")+
  theme_bw()+
  theme(axis.text.x=element_blank(),
        axis.ticks = element_blank(),
        text = element_text(size = 13))
```


Plots of CO2


Interval
```{r}
g0 <- vw2_week%>%
  filter(ClosestStart>0) 

slopes_for_plot <- slope_temp_int_3obs %>%
  filter(!is.na(slope_co2)) %>%
  mutate(y0 = slope_co2*as.numeric(Date_start)+intercept_co2,
         y1 = slope_co2*as.numeric(Date_end)+intercept_co2,
         Year = year(Date_start))
lim_bot <- min(slope_temp_int_3obs$slope_co2)
lim_top <- max(slope_temp_int_3obs$slope_co2)

jet.colors <- colorRampPalette(c("#00007F", "blue", "#007FFF", "cyan", "#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000"))

g0 %>%
  mutate(Year = year(Date))%>%
  ggplot(aes(x = as_datetime(Date),y = co2_vw_umolL))+
  geom_segment(aes(x = as_datetime(Date_start), 
                 y = y0, 
                 xend = as_datetime(Date_end), 
                 yend = y1, color = -slope_co2), data = slopes_for_plot,
             lwd = 3)+
  scale_color_gradientn(colours=jet.colors(7), limits = c(lim_bot,lim_top),na.value = "white")+
  geom_point(size = 2, pch = 1, alpha = 0.5)+
  facet_grid(cols = vars(Year), scales = "free_x",space = "free_x")+
  ylab("Average hypolimnetic CO2 (umol/L)")+
  xlab("")+
  theme_bw()+
  theme(axis.text.x=element_blank(),
        axis.ticks = element_blank(),
        text = element_text(size = 13))
```

Week
```{r}
g0 <- vw2_week%>%
  filter(ClosestStart>0) 

slopes_for_plot <- slope_temp_wk_2obs %>%
  filter(!is.na(slope_co2)) %>%
  mutate(y0 = slope_co2*as.numeric(Date_start)+intercept_co2,
         y1 = slope_co2*as.numeric(Date_end)+intercept_co2,
         Year = year(Date_start))
lim_bot <- min(-slope_temp_wk_2obs$slope_co2)
lim_top <- max(-slope_temp_wk_2obs$slope_co2)

jet.colors <- colorRampPalette(c("#00007F", "blue", "#007FFF", "cyan", "#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000"))

g0 %>%
  mutate(Year = year(Date))%>%
  ggplot(aes(x = as_datetime(Date),y = co2_vw_umolL))+
  geom_segment(aes(x = as_datetime(Date_start), 
                 y = y0, 
                 xend = as_datetime(Date_end), 
                 yend = y1, color = -slope_co2), data = slopes_for_plot,
             lwd = 3)+
  scale_color_gradientn(colours=jet.colors(7), limits = c(lim_bot,lim_top),na.value = "white")+
  geom_point(size = 2, pch = 1, alpha = 0.5)+
  facet_grid(cols = vars(Year), scales = "free_x",space = "free_x")+
  ylab("Average hypolimnetic CO2 (umol/L)")+
  xlab("")+
  theme_bw()+
  theme(axis.text.x=element_blank(),
        axis.ticks = element_blank(),
        text = element_text(size = 13))
```

Month
```{r}
g0 <- vw2_week%>%
  filter(ClosestStart>0) 

slopes_for_plot <- slope_temp_month %>%
  filter(!is.na(pw_slope_co2),
         Observations_co2>2) %>%
  filter(difftime(Date_end,Date_start) > 14)%>%
  mutate(y0 = pw_slope_co2*as.numeric(Date_start)+pw_intercept_co2,
         y1 = pw_slope_co2*as.numeric(Date_end)+pw_intercept_co2,
         Year = year(Date_start))
lim_bot <- min(slope_temp_month$pw_slope_co2)
lim_top <- max(slope_temp_month$pw_slope_co2)

jet.colors <- colorRampPalette(c("#00007F", "blue", "#007FFF", "cyan", "#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000"))

p = g0 %>%
  mutate(Year = year(Date))%>%
  ggplot(aes(x = as_datetime(Date),y = co2_vw_umolL))+
  geom_segment(aes(x = as_datetime(Date_start), 
                 y = y0, 
                 xend = as_datetime(Date_end), 
                 yend = y1, color = slope_co2), data = slopes_for_plot,
             lwd = 3)+
  scale_color_gradientn(colours=jet.colors(7), limits = c(lim_bot,lim_top),na.value = "white")+
  geom_point(size = 2, pch = 1, alpha = 0.5)+
  facet_grid(cols = vars(Year), scales = "free_x",space = "free_x")+
  ylab("Average hypolimnetic CO2 (umol/L)")+
  xlab("")+
  theme_bw()+
  theme(
        axis.ticks = element_blank(),
        text = element_text(size = 13))

jpeg("co2_month_intervals.jpg",width = 6, height = 4, units = "in", res = 300)
p
dev.off()
p
```